import i18nConfig from '@/i18nConfig';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Cairo } from 'next/font/google';
import { ReactNode } from 'react';
import { dir } from 'i18next';
import { notFound } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const cairo = Cairo({
	subsets: ["latin", "arabic"],
  weight: ['400', '700'],
});

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout(props: {
  children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await props.params;
  const { children } = props;

  if (!i18nConfig.locales.includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale} dir={dir(locale)} className={cairo.className}>
      <body>{children}</body>
    </html>
  );
}
